---
# handlers file for roles/le_cert
- name: Remove nginx defaults
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default

- name: Lets Encrypt nginx reload
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
    enabled: true
