---
- name: IPSec server install with using self signed certificate
  hosts: all
  become: true
  roles:
    - ss_cert
    - ipsec
  pre_tasks:
    - name: Ufw allow OpenSSH
      community.general.ufw:
        rule: allow
        name: OpenSSH
        comment: OpenSSH allow
  vars:
    ss_cert_ca_key: /etc/ipsec.d/private/ca.key
    ss_cert_ca_path: /etc/ipsec.d/cacerts/ca.pem
    ss_cert_key: /etc/ipsec.d/private/server-key.pem
    ss_cert_path: /etc/ipsec.d/certs/server-cert.crt
