---
- name: Import OS specific tasks
  ansible.builtin.include_tasks: "http_{{ ansible_os_family | lower }}.yml"

- name: Configure nginx
  ansible.builtin.template:
    src: le_cert.conf.j2
    dest: /etc/nginx/sites-available/le_cert.conf
    mode: '0644'

- name: Symlink for nginx Configure
  ansible.builtin.file:
    state: link
    src: /etc/nginx/sites-available/le_cert.conf
    dest: /etc/nginx/sites-enabled/le_cert.conf
    mode: '0644'
  notify:
    - Lets Encrypt nginx reload

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Begin Let's Encrypt challenges
  community.crypto.acme_certificate:
    acme_directory: "{{ le_cert_acme_directory }}"
    acme_version: "{{ le_cert_acme_version }}"
    account_key_src: "{{ le_cert_account_key }}"
    account_email: "{{ le_cert_acme_email }}"
    terms_agreed: true
    challenge: "{{ le_cert_acme_challenge_type }}"
    csr: "{{ le_cert_csrs_dir }}/{{ domain_name }}.csr"
    dest: "{{ le_cert_certs_dir }}/{{ domain_name }}.crt"
    fullchain_dest: "{{ le_cert_certs_dir }}/fullchain_{{ domain_name }}.crt"
    remaining_days: 91
  register: acme_challenge_your_domain

- name: Challenge Let`s Encrypt certificate
  when: acme_challenge_your_domain.challenge_data|map('length')|sum > 0
  block:
    - name: Implement http-01 challenge files
      ansible.builtin.copy:
        content: "{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource_value'] }}"
        dest: "/var/www/html/{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource'] }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - "{{ domain_name }}"

    - name: Complete Let's Encrypt challenges
      community.crypto.acme_certificate:
        acme_directory: "{{ le_cert_acme_directory }}"
        acme_version: "{{ le_cert_acme_version }}"
        account_key_src: "{{ le_cert_account_key }}"
        account_email: "{{ le_cert_acme_email }}"
        challenge: "{{ le_cert_acme_challenge_type }}"
        csr: "{{ le_cert_csrs_dir }}/{{ domain_name }}.csr"
        dest: "{{ le_cert_certs_dir }}/{{ domain_name }}.crt"
        chain_dest: "{{ le_cert_certs_dir }}/chain_{{ domain_name }}.crt"
        fullchain_dest: "{{ le_cert_certs_dir }}/fullchain_{{ domain_name }}"
        data: "{{ acme_challenge_your_domain }}"
